name: Deploy to NearlyFreeSpeech
on:
  push:
    branches: [ main ]  # Change to 'master' if that's your default branch
jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Deploy to NearlyFreeSpeech
      run: |
        mkdir -p ~/.ssh
        
        ssh-keyscan -H ssh.phx.nearlyfreespeech.net >> ~/.ssh/known_hosts
        
        sudo apt-get update
        sudo apt-get install -y sshpass
        
        sshpass -p "${{ secrets.SFTP_PASSWORD }}" rsync -avz --delete \
          --exclude='.git*' \
          --exclude='README.md' \
          --exclude='.github' \
          --exclude='node_modules' \
          ./ "${{ secrets.SFTP_USERNAME }}@${{ secrets.SFTP_HOST }}:/home/public/"
      env:
        SSHPASS: ${{ secrets.SFTP_PASSWORD }}
