name: Deploy to NearlyFreeSpeech

# Trigger this workflow when code is pushed to the main branch
on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Deploy to NearlyFreeSpeech
      uses: wlixcc/SFTP-Deploy-Action@v1.2.4
      with:
        
        server: ${{ secrets.SFTP_HOST }}
        username: ${{ secrets.SFTP_USERNAME }}
        password: ${{ secrets.SFTP_PASSWORD }}
        port: 22
        
        local_path: './*'
        remote_path: '/home/public'
        
