name: Debug Deploy to NearlyFreeSpeech

on:
  push:
    branches: [ main ]

jobs:
  debug:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Debug Connection
      run: |
        echo "Testing connection to NearlyFreeSpeech..."
        echo "Host: ${{ secrets.SFTP_HOST }}"
        echo "Username: ${{ secrets.SFTP_USERNAME }}"
        echo "Username length: ${#SFTP_USERNAME}"
        
        sudo apt-get update
        sudo apt-get install -y sshpass
        
        sshpass -p "${{ secrets.SFTP_PASSWORD }}" ssh -v -o StrictHostKeyChecking=no \
          "${{ secrets.SFTP_USERNAME }}@${{ secrets.SFTP_HOST }}" "pwd && ls -la"
      env:
        SFTP_USERNAME: ${{ secrets.SFTP_USERNAME }}
        SSHPASS: ${{ secrets.SFTP_PASSWORD }}
